#!/bin/bash

# install nala if it's missing
if ! command -v nala >/dev/null 2>&1; then
    echo "Installing nala"
    if [[ $(lsb_release -rs) == "22.04" ]]; then
        sudo apt update && sudo apt install nala -y
    else
        echo "deb https://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
        wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
        sudo apt update && sudo apt install nala-legacy -y
    fi
fi

if [ ! -f "/etc/apt/sources.list.d/nala-sources.list" ]; then
    echo "Setup fastest mirror with nala"
    # get fastest mirror for Ubuntu packages
    yes | sudo nala fetch --auto
fi

sudo nala upgrade -y
