#!/bin/bash

# install build-essential
sudo nala install build-essential -y

# install Homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi
