#!/bin/sh

echo "Installing and setting up nvm 0.39.1"

# Install Node Version Manager (NVM) and configure it with .profile
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

. "$HOME/.nvm/nvm.sh"

echo "Installing the latest version of node"
nvm install node

echo "Installing pnpm"
nvm use node
npm install -g pnpm

echo "Installing Firebase CLI"
pnpm add -g firebase-tools
