#!/bin/sh

echo "Installing and setting up nvm"

# Install Node Version Manager (NVM) and configure it with .profile
if [ ! -d "$HOME/.nvm" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
fi
if ! command -v -- "nvm" > /dev/null 2>&1; then
    \. "$HOME/.nvm/nvm.sh"
fi

echo "Installing the latest version of node"
cd "$HOME/.nvm"
nvm install node

echo "Installing pnpm"
nvm use node
npm install -g pnpm
pnpm setup
export PNPM_HOME="/home/kaiden/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

echo "Installing Firebase CLI"
pnpm add -g firebase-tools
