#!/bin/bash

# Install unzip
if [ $(dpkg -s "unzip" | grep -c "ok installed") -eq 0 ] ||  [ $(dpkg -s "openjdk-17-jdk" | grep -c "ok installed") -eq 0 ]; then
    echo "Install unzip and OpenJDK 8"
    sudo nala install unzip openjdk-8-jdk -y
fi

if [ ! -d "/usr/lib/android-sdk/cmdline-tools" ]; then
    # Set up SDK dir
    echo "Set up Android SDK directory"
    sudo mkdir -p /usr/lib/android-sdk
    sudo chown kaiden:kaiden /usr/lib/android-sdk

    # Download Android CLI tool for sdkmanager
    echo "Download command line tool and run sdkmanager"
    wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    unzip ./commandlinetools-linux-8512546_latest.zip # extracted files are in 'cmdline-tools' dir
    yes | ./cmdline-tools/bin/sdkmanager --install "cmdline-tools;latest" --sdk_root=/usr/lib/android-sdk/
    sudo ln -s /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager /usr/local/sbin/sdkmanager

    # Clean up downloaded files
    rm -f ./commandlinetools-linux-8512546_latest.zip
    rm -rf ./cmdline-tools
fi

# Install various SDK and tools
yes | sdkmanager --install "build-tools;33.0.0" "platform-tools" "platforms;android-29" "platforms;android-30" "platforms;android-31" "platforms;android-32" "platforms;android-33"

# Create symlink for adb
sudo ln -s /usr/lib/android-sdk/platform-tools/adb /usr/local/sbin/adb
