#!/bin/bash

# Load homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

echo "Installing & setting up Flutter"

fvm install stable

echo "Installing FlutterFire CLI"
dart pub global activate flutterfire_cli
