#!/bin/bash

# Load homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

echo "Installing & setting up Flutter"

fvm install stable

# install FlutterFire only if flutterfire command doesn't exist
export PATH="$PATH":"$HOME/.pub-cache/bin"
if ! command -v flutterfire >/dev/null 2>&1; then
    echo "Installing FlutterFire CLI"
    dart pub global activate flutterfire_cli
fi
